CUDA_VISIBLE_DEVICES=7 python main.py\
	--data_path '../data/processed_data/amazon/'\
	--evaluation_file '../results/amazon/test_scibert_time.csv'\
	--evaluation_file_val '../results/amazon/val_scibert_time.csv'\
	--epochs_mil 20\
	--epochs_mil_retrain 20\
	--weight_dir '../results/amazon/weight/'\
	--embedding_type 'scibert'\
	--compute_embedding 0\
	--max_iter 10\
	--shuffle 1\
